// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package iso

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	PackerBuildName           *string           `mapstructure:"packer_build_name" cty:"packer_build_name" hcl:"packer_build_name"`
	PackerBuilderType         *string           `mapstructure:"packer_builder_type" cty:"packer_builder_type" hcl:"packer_builder_type"`
	PackerCoreVersion         *string           `mapstructure:"packer_core_version" cty:"packer_core_version" hcl:"packer_core_version"`
	PackerDebug               *bool             `mapstructure:"packer_debug" cty:"packer_debug" hcl:"packer_debug"`
	PackerForce               *bool             `mapstructure:"packer_force" cty:"packer_force" hcl:"packer_force"`
	PackerOnError             *string           `mapstructure:"packer_on_error" cty:"packer_on_error" hcl:"packer_on_error"`
	PackerUserVars            map[string]string `mapstructure:"packer_user_variables" cty:"packer_user_variables" hcl:"packer_user_variables"`
	PackerSensitiveVars       []string          `mapstructure:"packer_sensitive_variables" cty:"packer_sensitive_variables" hcl:"packer_sensitive_variables"`
	Type                      *string           `mapstructure:"communicator" cty:"communicator" hcl:"communicator"`
	PauseBeforeConnect        *string           `mapstructure:"pause_before_connecting" cty:"pause_before_connecting" hcl:"pause_before_connecting"`
	SSHHost                   *string           `mapstructure:"ssh_host" cty:"ssh_host" hcl:"ssh_host"`
	SSHPort                   *int              `mapstructure:"ssh_port" cty:"ssh_port" hcl:"ssh_port"`
	SSHUsername               *string           `mapstructure:"ssh_username" cty:"ssh_username" hcl:"ssh_username"`
	SSHPassword               *string           `mapstructure:"ssh_password" cty:"ssh_password" hcl:"ssh_password"`
	SSHKeyPairName            *string           `mapstructure:"ssh_keypair_name" undocumented:"true" cty:"ssh_keypair_name" hcl:"ssh_keypair_name"`
	SSHTemporaryKeyPairName   *string           `mapstructure:"temporary_key_pair_name" undocumented:"true" cty:"temporary_key_pair_name" hcl:"temporary_key_pair_name"`
	SSHTemporaryKeyPairType   *string           `mapstructure:"temporary_key_pair_type" cty:"temporary_key_pair_type" hcl:"temporary_key_pair_type"`
	SSHTemporaryKeyPairBits   *int              `mapstructure:"temporary_key_pair_bits" cty:"temporary_key_pair_bits" hcl:"temporary_key_pair_bits"`
	SSHCiphers                []string          `mapstructure:"ssh_ciphers" cty:"ssh_ciphers" hcl:"ssh_ciphers"`
	SSHClearAuthorizedKeys    *bool             `mapstructure:"ssh_clear_authorized_keys" cty:"ssh_clear_authorized_keys" hcl:"ssh_clear_authorized_keys"`
	SSHKEXAlgos               []string          `mapstructure:"ssh_key_exchange_algorithms" cty:"ssh_key_exchange_algorithms" hcl:"ssh_key_exchange_algorithms"`
	SSHPrivateKeyFile         *string           `mapstructure:"ssh_private_key_file" undocumented:"true" cty:"ssh_private_key_file" hcl:"ssh_private_key_file"`
	SSHCertificateFile        *string           `mapstructure:"ssh_certificate_file" cty:"ssh_certificate_file" hcl:"ssh_certificate_file"`
	SSHPty                    *bool             `mapstructure:"ssh_pty" cty:"ssh_pty" hcl:"ssh_pty"`
	SSHTimeout                *string           `mapstructure:"ssh_timeout" cty:"ssh_timeout" hcl:"ssh_timeout"`
	SSHWaitTimeout            *string           `mapstructure:"ssh_wait_timeout" undocumented:"true" cty:"ssh_wait_timeout" hcl:"ssh_wait_timeout"`
	SSHAgentAuth              *bool             `mapstructure:"ssh_agent_auth" undocumented:"true" cty:"ssh_agent_auth" hcl:"ssh_agent_auth"`
	SSHDisableAgentForwarding *bool             `mapstructure:"ssh_disable_agent_forwarding" cty:"ssh_disable_agent_forwarding" hcl:"ssh_disable_agent_forwarding"`
	SSHHandshakeAttempts      *int              `mapstructure:"ssh_handshake_attempts" cty:"ssh_handshake_attempts" hcl:"ssh_handshake_attempts"`
	SSHBastionHost            *string           `mapstructure:"ssh_bastion_host" cty:"ssh_bastion_host" hcl:"ssh_bastion_host"`
	SSHBastionPort            *int              `mapstructure:"ssh_bastion_port" cty:"ssh_bastion_port" hcl:"ssh_bastion_port"`
	SSHBastionAgentAuth       *bool             `mapstructure:"ssh_bastion_agent_auth" cty:"ssh_bastion_agent_auth" hcl:"ssh_bastion_agent_auth"`
	SSHBastionUsername        *string           `mapstructure:"ssh_bastion_username" cty:"ssh_bastion_username" hcl:"ssh_bastion_username"`
	SSHBastionPassword        *string           `mapstructure:"ssh_bastion_password" cty:"ssh_bastion_password" hcl:"ssh_bastion_password"`
	SSHBastionInteractive     *bool             `mapstructure:"ssh_bastion_interactive" cty:"ssh_bastion_interactive" hcl:"ssh_bastion_interactive"`
	SSHBastionPrivateKeyFile  *string           `mapstructure:"ssh_bastion_private_key_file" cty:"ssh_bastion_private_key_file" hcl:"ssh_bastion_private_key_file"`
	SSHBastionCertificateFile *string           `mapstructure:"ssh_bastion_certificate_file" cty:"ssh_bastion_certificate_file" hcl:"ssh_bastion_certificate_file"`
	SSHFileTransferMethod     *string           `mapstructure:"ssh_file_transfer_method" cty:"ssh_file_transfer_method" hcl:"ssh_file_transfer_method"`
	SSHProxyHost              *string           `mapstructure:"ssh_proxy_host" cty:"ssh_proxy_host" hcl:"ssh_proxy_host"`
	SSHProxyPort              *int              `mapstructure:"ssh_proxy_port" cty:"ssh_proxy_port" hcl:"ssh_proxy_port"`
	SSHProxyUsername          *string           `mapstructure:"ssh_proxy_username" cty:"ssh_proxy_username" hcl:"ssh_proxy_username"`
	SSHProxyPassword          *string           `mapstructure:"ssh_proxy_password" cty:"ssh_proxy_password" hcl:"ssh_proxy_password"`
	SSHKeepAliveInterval      *string           `mapstructure:"ssh_keep_alive_interval" cty:"ssh_keep_alive_interval" hcl:"ssh_keep_alive_interval"`
	SSHReadWriteTimeout       *string           `mapstructure:"ssh_read_write_timeout" cty:"ssh_read_write_timeout" hcl:"ssh_read_write_timeout"`
	SSHRemoteTunnels          []string          `mapstructure:"ssh_remote_tunnels" cty:"ssh_remote_tunnels" hcl:"ssh_remote_tunnels"`
	SSHLocalTunnels           []string          `mapstructure:"ssh_local_tunnels" cty:"ssh_local_tunnels" hcl:"ssh_local_tunnels"`
	SSHPublicKey              []byte            `mapstructure:"ssh_public_key" undocumented:"true" cty:"ssh_public_key" hcl:"ssh_public_key"`
	SSHPrivateKey             []byte            `mapstructure:"ssh_private_key" undocumented:"true" cty:"ssh_private_key" hcl:"ssh_private_key"`
	WinRMUser                 *string           `mapstructure:"winrm_username" cty:"winrm_username" hcl:"winrm_username"`
	WinRMPassword             *string           `mapstructure:"winrm_password" cty:"winrm_password" hcl:"winrm_password"`
	WinRMHost                 *string           `mapstructure:"winrm_host" cty:"winrm_host" hcl:"winrm_host"`
	WinRMNoProxy              *bool             `mapstructure:"winrm_no_proxy" cty:"winrm_no_proxy" hcl:"winrm_no_proxy"`
	WinRMPort                 *int              `mapstructure:"winrm_port" cty:"winrm_port" hcl:"winrm_port"`
	WinRMTimeout              *string           `mapstructure:"winrm_timeout" cty:"winrm_timeout" hcl:"winrm_timeout"`
	WinRMUseSSL               *bool             `mapstructure:"winrm_use_ssl" cty:"winrm_use_ssl" hcl:"winrm_use_ssl"`
	WinRMInsecure             *bool             `mapstructure:"winrm_insecure" cty:"winrm_insecure" hcl:"winrm_insecure"`
	WinRMUseNTLM              *bool             `mapstructure:"winrm_use_ntlm" cty:"winrm_use_ntlm" hcl:"winrm_use_ntlm"`
	Label                     *string           `mapstructure:"media_label" required:"false" cty:"media_label" hcl:"media_label"`
	Files                     []string          `mapstructure:"media_files" required:"false" cty:"media_files" hcl:"media_files"`
	Content                   map[string]string `mapstructure:"media_content" required:"false" cty:"media_content" hcl:"media_content"`
	Keep                      *bool             `mapstructure:"keep_media" required:"false" cty:"keep_media" hcl:"keep_media"`
	WaitTimeout               *string           `mapstructure:"ip_wait_timeout" cty:"ip_wait_timeout" hcl:"ip_wait_timeout"`
	SettleTimeout             *string           `mapstructure:"ip_settle_timeout" cty:"ip_settle_timeout" hcl:"ip_settle_timeout"`
	DisableForwarding         *bool             `mapstructure:"disable_forwarding" required:"false" cty:"disable_forwarding" hcl:"disable_forwarding"`
	ForwardingPort            *int              `mapstructure:"forwarding_port" required:"false" cty:"forwarding_port" hcl:"forwarding_port"`
	AgentWaitTimeout          *string           `mapstructure:"agent_wait_timeout" required:"false" cty:"agent_wait_timeout" hcl:"agent_wait_timeout"`
	KubeConfig                *string           `mapstructure:"kube_config" required:"true" cty:"kube_config" hcl:"kube_config"`
	Name                      *string           `mapstructure:"name" required:"false" undocumented:"true" cty:"name" hcl:"name"`
	TemplateName              *string           `mapstructure:"template_name" required:"true" cty:"template_name" hcl:"template_name"`
	VMName                    *string           `mapstructure:"vm_name" required:"false" cty:"vm_name" hcl:"vm_name"`
	Namespace                 *string           `mapstructure:"namespace" required:"true" cty:"namespace" hcl:"namespace"`
	IsoVolumeName             *string           `mapstructure:"iso_volume_name" required:"true" cty:"iso_volume_name" hcl:"iso_volume_name"`
	DiskSize                  *string           `mapstructure:"disk_size" required:"true" cty:"disk_size" hcl:"disk_size"`
	StorageClassName          *string           `mapstructure:"storage_class_name" required:"false" cty:"storage_class_name" hcl:"storage_class_name"`
	AccessMode                *string           `mapstructure:"access_mode" required:"false" cty:"access_mode" hcl:"access_mode"`
	VolumeMode                *string           `mapstructure:"volume_mode" required:"false" cty:"volume_mode" hcl:"volume_mode"`
	InstanceType              *string           `mapstructure:"instance_type" required:"false" cty:"instance_type" hcl:"instance_type"`
	InstanceTypeKind          *string           `mapstructure:"instance_type_kind" required:"false" cty:"instance_type_kind" hcl:"instance_type_kind"`
	Preference                *string           `mapstructure:"preference" required:"false" cty:"preference" hcl:"preference"`
	PreferenceKind            *string           `mapstructure:"preference_kind" required:"false" cty:"preference_kind" hcl:"preference_kind"`
	Memory                    *string           `mapstructure:"memory" required:"false" cty:"memory" hcl:"memory"`
	CPU                       *uint32           `mapstructure:"cpu" required:"false" cty:"cpu" hcl:"cpu"`
	OperatingSystemType       *string           `mapstructure:"os_type" required:"false" cty:"os_type" hcl:"os_type"`
	Networks                  []FlatNetwork     `mapstructure:"networks" required:"false" cty:"networks" hcl:"networks"`
	BootCommand               []string          `mapstructure:"boot_command" required:"false" cty:"boot_command" hcl:"boot_command"`
	BootWait                  *string           `mapstructure:"boot_wait" required:"false" cty:"boot_wait" hcl:"boot_wait"`
	InstallationWaitTimeout   *string           `mapstructure:"installation_wait_timeout" required:"false" cty:"installation_wait_timeout" hcl:"installation_wait_timeout"`
	SSHLocalPort              *int              `mapstructure:"ssh_local_port" required:"false" cty:"ssh_local_port" hcl:"ssh_local_port"`
	SSHRemotePort             *int              `mapstructure:"ssh_remote_port" required:"false" undocumented:"true" cty:"ssh_remote_port" hcl:"ssh_remote_port"`
	VirtIOContainer           *string           `mapstructure:"virtio_container" required:"false" cty:"virtio_container" hcl:"virtio_container"`
	WinRMLocalPort            *int              `mapstructure:"winrm_local_port" required:"false" cty:"winrm_local_port" hcl:"winrm_local_port"`
	WinRMRemotePort           *int              `mapstructure:"winrm_remote_port" required:"false" undocumented:"true" cty:"winrm_remote_port" hcl:"winrm_remote_port"`
	WinRMWaitTimeout          *string           `mapstructure:"winrm_wait_timeout" required:"false" undocumented:"true" cty:"winrm_wait_timeout" hcl:"winrm_wait_timeout"`
	KeepVM                    *bool             `mapstructure:"keep_vm" required:"false" cty:"keep_vm" hcl:"keep_vm"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"packer_build_name":            &hcldec.AttrSpec{Name: "packer_build_name", Type: cty.String, Required: false},
		"packer_builder_type":          &hcldec.AttrSpec{Name: "packer_builder_type", Type: cty.String, Required: false},
		"packer_core_version":          &hcldec.AttrSpec{Name: "packer_core_version", Type: cty.String, Required: false},
		"packer_debug":                 &hcldec.AttrSpec{Name: "packer_debug", Type: cty.Bool, Required: false},
		"packer_force":                 &hcldec.AttrSpec{Name: "packer_force", Type: cty.Bool, Required: false},
		"packer_on_error":              &hcldec.AttrSpec{Name: "packer_on_error", Type: cty.String, Required: false},
		"packer_user_variables":        &hcldec.AttrSpec{Name: "packer_user_variables", Type: cty.Map(cty.String), Required: false},
		"packer_sensitive_variables":   &hcldec.AttrSpec{Name: "packer_sensitive_variables", Type: cty.List(cty.String), Required: false},
		"communicator":                 &hcldec.AttrSpec{Name: "communicator", Type: cty.String, Required: false},
		"pause_before_connecting":      &hcldec.AttrSpec{Name: "pause_before_connecting", Type: cty.String, Required: false},
		"ssh_host":                     &hcldec.AttrSpec{Name: "ssh_host", Type: cty.String, Required: false},
		"ssh_port":                     &hcldec.AttrSpec{Name: "ssh_port", Type: cty.Number, Required: false},
		"ssh_username":                 &hcldec.AttrSpec{Name: "ssh_username", Type: cty.String, Required: false},
		"ssh_password":                 &hcldec.AttrSpec{Name: "ssh_password", Type: cty.String, Required: false},
		"ssh_keypair_name":             &hcldec.AttrSpec{Name: "ssh_keypair_name", Type: cty.String, Required: false},
		"temporary_key_pair_name":      &hcldec.AttrSpec{Name: "temporary_key_pair_name", Type: cty.String, Required: false},
		"temporary_key_pair_type":      &hcldec.AttrSpec{Name: "temporary_key_pair_type", Type: cty.String, Required: false},
		"temporary_key_pair_bits":      &hcldec.AttrSpec{Name: "temporary_key_pair_bits", Type: cty.Number, Required: false},
		"ssh_ciphers":                  &hcldec.AttrSpec{Name: "ssh_ciphers", Type: cty.List(cty.String), Required: false},
		"ssh_clear_authorized_keys":    &hcldec.AttrSpec{Name: "ssh_clear_authorized_keys", Type: cty.Bool, Required: false},
		"ssh_key_exchange_algorithms":  &hcldec.AttrSpec{Name: "ssh_key_exchange_algorithms", Type: cty.List(cty.String), Required: false},
		"ssh_private_key_file":         &hcldec.AttrSpec{Name: "ssh_private_key_file", Type: cty.String, Required: false},
		"ssh_certificate_file":         &hcldec.AttrSpec{Name: "ssh_certificate_file", Type: cty.String, Required: false},
		"ssh_pty":                      &hcldec.AttrSpec{Name: "ssh_pty", Type: cty.Bool, Required: false},
		"ssh_timeout":                  &hcldec.AttrSpec{Name: "ssh_timeout", Type: cty.String, Required: false},
		"ssh_wait_timeout":             &hcldec.AttrSpec{Name: "ssh_wait_timeout", Type: cty.String, Required: false},
		"ssh_agent_auth":               &hcldec.AttrSpec{Name: "ssh_agent_auth", Type: cty.Bool, Required: false},
		"ssh_disable_agent_forwarding": &hcldec.AttrSpec{Name: "ssh_disable_agent_forwarding", Type: cty.Bool, Required: false},
		"ssh_handshake_attempts":       &hcldec.AttrSpec{Name: "ssh_handshake_attempts", Type: cty.Number, Required: false},
		"ssh_bastion_host":             &hcldec.AttrSpec{Name: "ssh_bastion_host", Type: cty.String, Required: false},
		"ssh_bastion_port":             &hcldec.AttrSpec{Name: "ssh_bastion_port", Type: cty.Number, Required: false},
		"ssh_bastion_agent_auth":       &hcldec.AttrSpec{Name: "ssh_bastion_agent_auth", Type: cty.Bool, Required: false},
		"ssh_bastion_username":         &hcldec.AttrSpec{Name: "ssh_bastion_username", Type: cty.String, Required: false},
		"ssh_bastion_password":         &hcldec.AttrSpec{Name: "ssh_bastion_password", Type: cty.String, Required: false},
		"ssh_bastion_interactive":      &hcldec.AttrSpec{Name: "ssh_bastion_interactive", Type: cty.Bool, Required: false},
		"ssh_bastion_private_key_file": &hcldec.AttrSpec{Name: "ssh_bastion_private_key_file", Type: cty.String, Required: false},
		"ssh_bastion_certificate_file": &hcldec.AttrSpec{Name: "ssh_bastion_certificate_file", Type: cty.String, Required: false},
		"ssh_file_transfer_method":     &hcldec.AttrSpec{Name: "ssh_file_transfer_method", Type: cty.String, Required: false},
		"ssh_proxy_host":               &hcldec.AttrSpec{Name: "ssh_proxy_host", Type: cty.String, Required: false},
		"ssh_proxy_port":               &hcldec.AttrSpec{Name: "ssh_proxy_port", Type: cty.Number, Required: false},
		"ssh_proxy_username":           &hcldec.AttrSpec{Name: "ssh_proxy_username", Type: cty.String, Required: false},
		"ssh_proxy_password":           &hcldec.AttrSpec{Name: "ssh_proxy_password", Type: cty.String, Required: false},
		"ssh_keep_alive_interval":      &hcldec.AttrSpec{Name: "ssh_keep_alive_interval", Type: cty.String, Required: false},
		"ssh_read_write_timeout":       &hcldec.AttrSpec{Name: "ssh_read_write_timeout", Type: cty.String, Required: false},
		"ssh_remote_tunnels":           &hcldec.AttrSpec{Name: "ssh_remote_tunnels", Type: cty.List(cty.String), Required: false},
		"ssh_local_tunnels":            &hcldec.AttrSpec{Name: "ssh_local_tunnels", Type: cty.List(cty.String), Required: false},
		"ssh_public_key":               &hcldec.AttrSpec{Name: "ssh_public_key", Type: cty.List(cty.Number), Required: false},
		"ssh_private_key":              &hcldec.AttrSpec{Name: "ssh_private_key", Type: cty.List(cty.Number), Required: false},
		"winrm_username":               &hcldec.AttrSpec{Name: "winrm_username", Type: cty.String, Required: false},
		"winrm_password":               &hcldec.AttrSpec{Name: "winrm_password", Type: cty.String, Required: false},
		"winrm_host":                   &hcldec.AttrSpec{Name: "winrm_host", Type: cty.String, Required: false},
		"winrm_no_proxy":               &hcldec.AttrSpec{Name: "winrm_no_proxy", Type: cty.Bool, Required: false},
		"winrm_port":                   &hcldec.AttrSpec{Name: "winrm_port", Type: cty.Number, Required: false},
		"winrm_timeout":                &hcldec.AttrSpec{Name: "winrm_timeout", Type: cty.String, Required: false},
		"winrm_use_ssl":                &hcldec.AttrSpec{Name: "winrm_use_ssl", Type: cty.Bool, Required: false},
		"winrm_insecure":               &hcldec.AttrSpec{Name: "winrm_insecure", Type: cty.Bool, Required: false},
		"winrm_use_ntlm":               &hcldec.AttrSpec{Name: "winrm_use_ntlm", Type: cty.Bool, Required: false},
		"media_label":                  &hcldec.AttrSpec{Name: "media_label", Type: cty.String, Required: false},
		"media_files":                  &hcldec.AttrSpec{Name: "media_files", Type: cty.List(cty.String), Required: false},
		"media_content":                &hcldec.AttrSpec{Name: "media_content", Type: cty.Map(cty.String), Required: false},
		"keep_media":                   &hcldec.AttrSpec{Name: "keep_media", Type: cty.Bool, Required: false},
		"ip_wait_timeout":              &hcldec.AttrSpec{Name: "ip_wait_timeout", Type: cty.String, Required: false},
		"ip_settle_timeout":            &hcldec.AttrSpec{Name: "ip_settle_timeout", Type: cty.String, Required: false},
		"disable_forwarding":           &hcldec.AttrSpec{Name: "disable_forwarding", Type: cty.Bool, Required: false},
		"forwarding_port":              &hcldec.AttrSpec{Name: "forwarding_port", Type: cty.Number, Required: false},
		"agent_wait_timeout":           &hcldec.AttrSpec{Name: "agent_wait_timeout", Type: cty.String, Required: false},
		"kube_config":                  &hcldec.AttrSpec{Name: "kube_config", Type: cty.String, Required: false},
		"name":                         &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"template_name":                &hcldec.AttrSpec{Name: "template_name", Type: cty.String, Required: false},
		"vm_name":                      &hcldec.AttrSpec{Name: "vm_name", Type: cty.String, Required: false},
		"namespace":                    &hcldec.AttrSpec{Name: "namespace", Type: cty.String, Required: false},
		"iso_volume_name":              &hcldec.AttrSpec{Name: "iso_volume_name", Type: cty.String, Required: false},
		"disk_size":                    &hcldec.AttrSpec{Name: "disk_size", Type: cty.String, Required: false},
		"storage_class_name":           &hcldec.AttrSpec{Name: "storage_class_name", Type: cty.String, Required: false},
		"access_mode":                  &hcldec.AttrSpec{Name: "access_mode", Type: cty.String, Required: false},
		"volume_mode":                  &hcldec.AttrSpec{Name: "volume_mode", Type: cty.String, Required: false},
		"instance_type":                &hcldec.AttrSpec{Name: "instance_type", Type: cty.String, Required: false},
		"instance_type_kind":           &hcldec.AttrSpec{Name: "instance_type_kind", Type: cty.String, Required: false},
		"preference":                   &hcldec.AttrSpec{Name: "preference", Type: cty.String, Required: false},
		"preference_kind":              &hcldec.AttrSpec{Name: "preference_kind", Type: cty.String, Required: false},
		"memory":                       &hcldec.AttrSpec{Name: "memory", Type: cty.String, Required: false},
		"cpu":                          &hcldec.AttrSpec{Name: "cpu", Type: cty.Number, Required: false},
		"os_type":                      &hcldec.AttrSpec{Name: "os_type", Type: cty.String, Required: false},
		"networks":                     &hcldec.BlockListSpec{TypeName: "networks", Nested: hcldec.ObjectSpec((*FlatNetwork)(nil).HCL2Spec())},
		"boot_command":                 &hcldec.AttrSpec{Name: "boot_command", Type: cty.List(cty.String), Required: false},
		"boot_wait":                    &hcldec.AttrSpec{Name: "boot_wait", Type: cty.String, Required: false},
		"installation_wait_timeout":    &hcldec.AttrSpec{Name: "installation_wait_timeout", Type: cty.String, Required: false},
		"ssh_local_port":               &hcldec.AttrSpec{Name: "ssh_local_port", Type: cty.Number, Required: false},
		"ssh_remote_port":              &hcldec.AttrSpec{Name: "ssh_remote_port", Type: cty.Number, Required: false},
		"virtio_container":             &hcldec.AttrSpec{Name: "virtio_container", Type: cty.String, Required: false},
		"winrm_local_port":             &hcldec.AttrSpec{Name: "winrm_local_port", Type: cty.Number, Required: false},
		"winrm_remote_port":            &hcldec.AttrSpec{Name: "winrm_remote_port", Type: cty.Number, Required: false},
		"winrm_wait_timeout":           &hcldec.AttrSpec{Name: "winrm_wait_timeout", Type: cty.String, Required: false},
		"keep_vm":                      &hcldec.AttrSpec{Name: "keep_vm", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatMultusNetwork is an auto-generated flat version of MultusNetwork.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatMultusNetwork struct {
	NetworkName *string `mapstructure:"networkName" cty:"networkName" hcl:"networkName"`
	Default     *bool   `mapstructure:"default,omitempty" cty:"default" hcl:"default"`
}

// FlatMapstructure returns a new FlatMultusNetwork.
// FlatMultusNetwork is an auto-generated flat version of MultusNetwork.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*MultusNetwork) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatMultusNetwork)
}

// HCL2Spec returns the hcl spec of a MultusNetwork.
// This spec is used by HCL to read the fields of MultusNetwork.
// The decoded values from this spec will then be applied to a FlatMultusNetwork.
func (*FlatMultusNetwork) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"networkName": &hcldec.AttrSpec{Name: "networkName", Type: cty.String, Required: false},
		"default":     &hcldec.AttrSpec{Name: "default", Type: cty.Bool, Required: false},
	}
	return s
}

// FlatNetwork is an auto-generated flat version of Network.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNetwork struct {
	Name   *string            `mapstructure:"name" cty:"name" hcl:"name"`
	Pod    *FlatPodNetwork    `mapstructure:"pod" cty:"pod" hcl:"pod"`
	Multus *FlatMultusNetwork `mapstructure:"multus" cty:"multus" hcl:"multus"`
}

// FlatMapstructure returns a new FlatNetwork.
// FlatNetwork is an auto-generated flat version of Network.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Network) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatNetwork)
}

// HCL2Spec returns the hcl spec of a Network.
// This spec is used by HCL to read the fields of Network.
// The decoded values from this spec will then be applied to a FlatNetwork.
func (*FlatNetwork) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"name":   &hcldec.AttrSpec{Name: "name", Type: cty.String, Required: false},
		"pod":    &hcldec.BlockSpec{TypeName: "pod", Nested: hcldec.ObjectSpec((*FlatPodNetwork)(nil).HCL2Spec())},
		"multus": &hcldec.BlockSpec{TypeName: "multus", Nested: hcldec.ObjectSpec((*FlatMultusNetwork)(nil).HCL2Spec())},
	}
	return s
}

// FlatNetworkSource is an auto-generated flat version of NetworkSource.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatNetworkSource struct {
	Pod    *FlatPodNetwork    `mapstructure:"pod" cty:"pod" hcl:"pod"`
	Multus *FlatMultusNetwork `mapstructure:"multus" cty:"multus" hcl:"multus"`
}

// FlatMapstructure returns a new FlatNetworkSource.
// FlatNetworkSource is an auto-generated flat version of NetworkSource.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*NetworkSource) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatNetworkSource)
}

// HCL2Spec returns the hcl spec of a NetworkSource.
// This spec is used by HCL to read the fields of NetworkSource.
// The decoded values from this spec will then be applied to a FlatNetworkSource.
func (*FlatNetworkSource) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"pod":    &hcldec.BlockSpec{TypeName: "pod", Nested: hcldec.ObjectSpec((*FlatPodNetwork)(nil).HCL2Spec())},
		"multus": &hcldec.BlockSpec{TypeName: "multus", Nested: hcldec.ObjectSpec((*FlatMultusNetwork)(nil).HCL2Spec())},
	}
	return s
}

// FlatPodNetwork is an auto-generated flat version of PodNetwork.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatPodNetwork struct {
	VMNetworkCIDR     *string `mapstructure:"vmNetworkCIDR,omitempty" cty:"vmNetworkCIDR" hcl:"vmNetworkCIDR"`
	VMIPv6NetworkCIDR *string `mapstructure:"vmIPv6NetworkCIDR,omitempty" cty:"vmIPv6NetworkCIDR" hcl:"vmIPv6NetworkCIDR"`
}

// FlatMapstructure returns a new FlatPodNetwork.
// FlatPodNetwork is an auto-generated flat version of PodNetwork.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*PodNetwork) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatPodNetwork)
}

// HCL2Spec returns the hcl spec of a PodNetwork.
// This spec is used by HCL to read the fields of PodNetwork.
// The decoded values from this spec will then be applied to a FlatPodNetwork.
func (*FlatPodNetwork) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"vmNetworkCIDR":     &hcldec.AttrSpec{Name: "vmNetworkCIDR", Type: cty.String, Required: false},
		"vmIPv6NetworkCIDR": &hcldec.AttrSpec{Name: "vmIPv6NetworkCIDR", Type: cty.String, Required: false},
	}
	return s
}
