// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package iso

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatMediaConfig is an auto-generated flat version of MediaConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatMediaConfig struct {
	Label   *string           `mapstructure:"media_label" required:"false" cty:"media_label" hcl:"media_label"`
	Files   []string          `mapstructure:"media_files" required:"false" cty:"media_files" hcl:"media_files"`
	Content map[string]string `mapstructure:"media_content" required:"false" cty:"media_content" hcl:"media_content"`
	Keep    *bool             `mapstructure:"keep_media" required:"false" cty:"keep_media" hcl:"keep_media"`
}

// FlatMapstructure returns a new FlatMediaConfig.
// FlatMediaConfig is an auto-generated flat version of MediaConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*MediaConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatMediaConfig)
}

// HCL2Spec returns the hcl spec of a MediaConfig.
// This spec is used by HCL to read the fields of MediaConfig.
// The decoded values from this spec will then be applied to a FlatMediaConfig.
func (*FlatMediaConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"media_label":   &hcldec.AttrSpec{Name: "media_label", Type: cty.String, Required: false},
		"media_files":   &hcldec.AttrSpec{Name: "media_files", Type: cty.List(cty.String), Required: false},
		"media_content": &hcldec.AttrSpec{Name: "media_content", Type: cty.Map(cty.String), Required: false},
		"keep_media":    &hcldec.AttrSpec{Name: "keep_media", Type: cty.Bool, Required: false},
	}
	return s
}
